# Generated by Django 5.1.1 on 2024-10-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stundet', to='crm.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
