# Generated by Django 5.1.1 on 2024-10-21 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_student_phone_number2_alter_student_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='User',
        ),
    ]
