# Generated by Django 5.1.1 on 2024-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Format: +998XXXXXXXXX', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number2',
            field=models.CharField(blank=True, help_text='Format: +998XXXXXXXXX', max_length=150, null=True),
        ),
    ]
